export enum EventType {
  CHARACTER_CREATED = "characterCreated",
  CHARACTER_UPDATED = "characterUpdated",
  FIGHT_STARTED = "fightStarted",
  FIGHT_COMPLETED = "fightCompleted",
  HEALING_STARTED = "healingStarted",
  HEALING_COMPLETED = "healingCompleted",
  RESURRECTION_STARTED = "resurrectionStarted",
  RESURRECTION_COMPLETED = "resurrectionCompleted",
  OPERATION_STARTED = "operationStarted",
  OPERATION_COMPLETED = "operationCompleted",
  OPERATION_FAILED = "operationFailed",
  POOLS_UPDATED = "poolsUpdated",
  LEADERBOARD_UPDATED = "leaderboardUpdated",
  CLAIMS_UPDATED = "claimsUpdated",
  CLAIM_STARTED = "claimStarted",
  CLAIM_COMPLETED = "claimCompleted",
  CLAIM_FAILED = "claimFailed",
  STATE_CHANGED = "stateChanged",
  ERROR_OCCURRED = "errorOccurred",
  VALIDATION_FAILED = "validationFailed",
  TRANSACTION_STATUS = "transactionStatus",
  CHARACTER_DATA_REFRESH = "characterDataRefresh",
}
