[environment]
from = "cfx:usdt"
to = "avax:usdt"
fromAddress = "0x5C01dc5D3047dB6Ae4E9A9B0946e2092a1a3A788"
recipient = "0x5C01dc5D3047dB6Ae4E9A9B0946e2092a1a3A788"
amount = 0.7
privateKey = ""

[project]
name = "cross-chain-pay-one-usdt"
version = "0.1.0"
description = "Picker startup template for nodejs project."
author = "openpick"
email = "openpicklabs@hotmail.com"
license = "MIT"

[task]
id = "b7e3a5d1-2c4f-41a7-b9d5-6a3c2b8d1e4f"
name = "Picker Nodejs task"
status = "Idle"
installed = "240128"
runs = 128
last_run = "240301"
