name: Codespaces prebuild

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm i -g pnpm@8

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "pnpm-lock.yaml found — attempting pnpm install --frozen-lockfile"
            pnpm install --frozen-lockfile || {
              echo "pnpm --frozen-lockfile failed (incompatible or missing lockfile). Retrying without --frozen-lockfile.";
              pnpm install --no-frozen-lockfile;
            }
          else
            echo "pnpm-lock.yaml not found — installing without --frozen-lockfile"
            pnpm install --no-frozen-lockfile
          fi

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Generate Vite build cache
        run: pnpm run build || true
