version: '3.8'

services:
  web-ui:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/app/dist
    command: ["pnpm", "preview", "--host", "0.0.0.0", "--port", "3000"]

  # Development service with hot reload
  web-ui-dev:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pnpm", "dev", "--host", "0.0.0.0", "--port", "5173"]
    profiles:
      - dev

